CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by VARCHAR(100),
    modified_on TIMESTAMP WITH TIME ZONE
);

CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    CONSTRAINT fk_item_product
        FOREIGN KEY (product_id)
        REFERENCES product (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_product_name ON product (product_name);
CREATE INDEX idx_product_created_on ON product (created_on);
CREATE INDEX idx_item_product_id ON item (product_id);
